### ISSUE TITLE
Audit all the smart contracts in the bridge

### ISSUE THREAD

**Issue by kfastov** [kfastov/worldcoin-bridge-linea#16]
## Overview
Conduct a comprehensive security audit of all smart contracts in the bridge, including abstract contracts.

## Scope
- LineaWorldID
- LineaStateBridge
- CrossDomainOwnableLinea
- Any other related contracts in the bridge system

## Tasks
1. Review each contract for potential security vulnerabilities
2. Analyze the interaction between contracts for any systemic risks
3. Check for common smart contract vulnerabilities (e.g., reentrancy, integer overflow/underflow, etc.)
4. Assess the overall security architecture of the bridge system
5. Provide a detailed report of findings, including severity levels and recommended fixes

## Acceptance Criteria
- [ ] Comprehensive audit report delivered, covering all contracts in scope
- [ ] Each identified issue is clearly described with its potential impact
- [ ] Recommendations for fixing or mitigating each issue are provided
- [ ] Overall assessment of the bridge's security is included in the report

## Additional Notes
- The audit should consider both individual contract security and the security of the entire bridge system as a whole
- Any assumptions made during the audit process should be clearly stated in the report

**Comment by DevPelz** [comment]
Hi @kfastov i proposed an audit service in one of the issues raised as i couldn't get you on telegram. should incase you don't have an audit team ready. We could discuss about it. here is my portfolio https://github.com/DevPelz

**Comment by kfastov** [comment]
Hey @DevPelz! I remember your message, and it would be great to have an audit later, though I think that the contracts are still a bit raw.
However we can discuss it in tg: https://t.me/worldcoin_linea_bridge https://t.me/kfastov
(sry if I missed your message)

**Comment by josephchimebuka** [comment]
Hello @kfastov i would also like to work on auditing the bridge contract when it's time. I would review the projects for errors and write unit test for them. I am on the telegram group and I have solved some issues on Only dust too.

**Comment by kfastov** [comment]
@josephchimebuka @DevPelz This issue is finally live and is a part of an ODHack 7.0, so you can apply via OnlyDust page 🙂

**Comment by ikemHood** [comment]
Hey @kfastov I woud love to audit the contracts.

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
Hey, I am ikem Peter. a fullstack software developer with 3+ years of working experience, I would love to help out with this issue...

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will employ the following comprehensive approach to solve the issue of conducting a security audit of the smart contracts in the bridge:

1. **Understand the System Architecture**: I will start by carefully analyzing the provided information to gain a deep understanding of the overall bridge system, its critical components, and the interactions between the different contracts. This includes the LineaWorldID, LineaStateBridge, CrossDomainOwnableLinea, and any other related contracts within the bridge system.

2. **Contract-level Security Review**: I will thoroughly review the code of each contract within the scope of the audit, paying close attention to the implementation of critical functions, access control mechanisms, and the use of external dependencies. This will involve checking for common smart contract vulnerabilities, such as reentrancy, integer overflow/underflow, and other known security issues.

3. **Interaction Analysis**: I will analyze the interactions between the different contracts within the bridge system, ensuring that the contract interfaces are designed securely and that the data passed between contracts is properly validated. I will identify any potential attack vectors that could arise from the way the contracts communicate and exchange data.

4. **Systemic Risk Assessment**: I will assess the overall security architecture of the bridge system, identifying potential single points of failure and examining the system's ability to withstand various attack scenarios. This will involve evaluating the quality of the access control mechanisms, privilege separation, and privilege escalation prevention.

5. **Documentation and Reporting**: I will document all the findings from the security audit, categorizing them by severity (e.g., critical, high, medium, low). For each finding, I will provide a clear and concise description of the issue, its potential impact, and a recommended fix or mitigation strategy. I will also highlight any systemic risks or architectural flaws that could affect the overall security of the bridge system. Finally, I will provide an overall assessment of the bridge's security posture and the level of confidence in the system's ability to withstand attacks.

6. **Comprehensive Audit Report**: I will deliver a comprehensive audit report that covers all the contracts within the scope, as per the acceptance criteria. The report will include the detailed findings, severity levels, and recommended fixes for each identified issue. It will also provide an overall assessment of the bridge's security and any recommendations for improving the system's security posture.

By following this approach, I aim to conduct a thorough and comprehensive security audit of the bridge system, identifying and addressing any potential vulnerabilities or security concerns to ensure the overall security and resilience of the system.

**Comment by DevSwayam** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
I have over 2 years of experience in EVM development and smart contract security, including privacy-focused applications and comprehensive audits. My background includes projects like custom bridges and modification in off chain infra for CCIP based bridges using hyperlane, demonstrating my expertise in identifying and addressing vulnerabilities related to offchain coordination projects.

### How I plan on tackling this issue
I’ll start by scoping the project and generating SLOC tables, including relevant protocol audit reports to understand potential future issues. I’ll then audit each contract, write fuzz tests, and prepare a detailed report with findings, mitigations, and improvements. My approach includes flow diagrams, invariant testing, and documentation enhancements. Relevant examples of my work can be found on my GitHub profile.

**Comment by codeZe-us** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
Software Engineer with key focus on Mobile applications with Blockchain Integrations. My stacks include, Swift, Kotlin, Solidity, Golang and Flutter.

### How I plan on tackling this issue
To address theses issues, firstly, for preparation, I will understand the purpose and functionality of each contract (LineaWorldID, LineaStateBridge, CrossDomainOwnableLinea), then analyze each contract individually for potential security vulnerabilities, secondly, I will identify critical functions, particularly those related to funds transfer, access control, and state changes.


For Inter-contract Analysis, evaluating how contracts interact by focusing on call chains, data flow, and dependencies between contracts will solve the issue.
After working on all these, I will procesd to checking for common  vulnerabilities like logic errors, incorrect inheritance structure, access control flaws, reentrancy.

Moving over to security architecture, I am to assess the overall security architecture of the bridge system by ensuring that contracts are designed with the principle of least privilege, and critical operations have sufficient safeguards. Also, incase of any assumptions made in the design or implementation of the contracts, I will validate these assumptions to ensure they are sound and do not introduce risks.

For Reporting, I will document all findings by categorising them by severity (Critical, High, Medium, Low). Then for each issue, I will provide a detailed explanation, including the potential impact and how it might be exploited. If any issue is identified, I will recommend fixes or mitigation strategies.

**Comment by bomanaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
I am a seasoned blockchain security engineer with hands-on experience in identifying and mitigating security vulnerabilities within smart contracts and blockchain systems. My background includes participating in smart contract security audits with platforms like Sherlock and CodeHawks, where I've successfully identified multiple high and medium-severity vulnerabilities. Specifically, I found four high and two medium vulnerabilities in a Sherlock audit and seven high and eight medium vulnerabilities in CodeHawks' FirstFlight.
Moreover, I contribute to the Grandine project as part of the EPF5 team, focusing on Ethereum consensus clients written in Rust. My role involves profiling and securing the consensus layer, giving me a deep understanding of blockchain architecture, consensus mechanisms, and the importance of ensuring secure and reliable operations across different layers of the blockchain stack.

### How I plan on tackling this issue
Review Each Contract for Potential Security Vulnerabilities
 Analyze the Interaction Between Contracts for Any Systemic Risks
Assess the Overall Security Architecture of the Bridge System
Write invariant test to improve and check the contract test structure
